FROM quay.io/kushansewmina/dark-shan-md-1
RUN git clone https://github.com/Tharusha69/DARK-SHAN-MD /root/Tharusha69
WORKDIR /root/Tharusha69/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]


